trigger:
  branches:
    include:
    - master
  paths:
    include:
    - artifact-passing-pipelines.yml

variables:
  skipComponentGovernanceDetection: true

stages:

- stage: Stage_1
  displayName: Stage 1

  jobs:

  - job: Job_S1_J1
    displayName: Stage 1 Job 1
    steps:
    - script: |
        echo "Stage 1, Job 1"
        echo "*** My Test Value Goes Here ***" > $(Build.ArtifactStagingDirectory)/outputs.txt
        cat $(Build.ArtifactStagingDirectory)/outputs.txt
      displayName: Build Pipeline Artifacts
    - task: PublishPipelineArtifact@0
      displayName: Publish Pipeline Artifacts
      # inputs:
      #   targetPath: './outputs.txt'

  - job: Job_S1_J2
    displayName: Stage 1 Job 2
    dependsOn: Job_S1_J1
    steps:
    - task: DownloadPipelineArtifact@0
      displayName: Download Pipeline Artifacts
    - script: |
        ls .
        cat ./outputs.txt
      displayName: Check Results

- stage: Stage_2
  displayName: Stage 2
  jobs:

  - job: Job_S2_J1
    displayName: Stage 2 Job 1
    steps:
    - task: DownloadPipelineArtifact@0
      displayName: Download Pipeline Artifacts
    - script: |
        ls .
        cat ./outputs.txt
      displayName: Check Results