trigger:
  branches:
    include:
    - master
  paths:
    include:
    - artifact-passing-pipelines.yml

variables:
  skipComponentGovernanceDetection: true

stages:

- stage: Stage_1
  displayName: Stage 1

  jobs:

  - job: Job_S1_J1
    displayName: Stage 1 Job 1
    steps:
    - script: |
        echo "Stage 1, Job 1"
        echo "*** My Test Value Goes Here ***" > $(build.artifactStagingDirectory)/outputs.txt
        cat $(build.artifactStagingDirectory)/outputs.txt
      displayName: Build Pipeline Artifacts
    - publish: $(build.artifactStagingDirectory)
      displayName: Publish Pipeline Artifacts
      artifact: myvariableartifact

  - job: Job_S1_J2
    displayName: Stage 1 Job 2
    dependsOn: Job_S1_J1
    steps:
    - download: current
      artifact: myvariableartifact
      displayName: Download Pipeline Artifacts
    - script: |
        ls $(pipeline.workspace)
        cat $(pipeline.workspace)/outputs.txt
      displayName: Check Results

- stage: Stage_2
  displayName: Stage 2
  jobs:

  - job: Job_S2_J1
    displayName: Stage 2 Job 1
    steps:
    - download: current
      artifact: myvariableartifact
      displayName: Download Pipeline Artifacts
    - script: |
        ls $(pipeline.workspace)
        cat $(pipeline.workspace)/outputs.txt
      displayName: Check Results