trigger:
  branches:
    include:
    - master
  paths:
    include:
    - artifact-passing-pipelines.yml

stages:

- stage: Stage_1
  displayName: Stage 1

  jobs:

  - job: Job_S1_J1
    displayName: Stage 1 Job 1
    steps:
    - script: |
        echo "Stage 1, Job 1"
        echo "My Test Value Goes Here" > $(Build.ArtifactStagingDirectory)/outputs.txt
        ls $(Build.ArtifactStagingDirectory)
        cat $(Build.ArtifactStagingDirectory)/outputs.txt
      displayName: Write Pipeline Artifact
    - task: PublishPipelineArtifact@0
      displayName: Publish Pipeline Artifact
      inputs:
        artifactName: 'MyOutputs'
        # targetPath: '$(Build.ArtifactStagingDirectory)/outputs.txt'

  - job: Job_S1_J2
    displayName: Stage 1 Job 2
    dependsOn: Job_S1_J1
    steps:
    - task: DownloadPipelineArtifact@0
      displayName: Prove Pipeline Artifact in Same Stage
      inputs:
    #     artifactName: 'MyOutputs'
    #     targetPath: .
    - script: |
        ls $(Build.ArtifactStagingDirectory)
        cat $(Build.ArtifactStagingDirectory)/outputs.txt

# - stage: Stage_2
#   displayName: Stage 2
#   jobs:

#   - job: Job_S2_J1
#     displayName: Stage 2 Job 1
#     steps:
#     - task: DownloadPipelineArtifact@0
#       displayName: Prove Pipeline Artifact in Different Stage
#       inputs:
#         artifactName: 'MyOutputs'
#         targetPath: .
#     - script: cat ./outputs.txt
