trigger:
  branches:
    include:
    - master
  paths:
    include:
    - job-variables-pipelines.yml

stages:
- stage: Stage_1
  displayName: Stage 1
  jobs:
  - job: Job_S1_J1
    displayName: Stage 1 Job 1
    steps:
    - bash: echo "Stage 1, Job 1"
  - job: Job_S1_J2
    displayName: Stage 1 Job 2
    steps:
    - bash: echo "Stage 1, Job 2"

- stage: Stage_2
  displayName: Stage 2
  jobs:
  - job: Job_S2_J1
    displayName: Stage 2 Job 1
    steps:
    - bash: echo "Stage 2, Job 1"
  - job: Job_S1_J2
    displayName: Stage 2 Job 2
    steps:
    - bash: echo "Stage 2, Job 2"