trigger:
  branches:
    include:
    - master
  paths:
    include:
    - job-variables-pipelines.yml

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Stage_1
  jobs:
  - job: Job S1.J1
    steps:
    - bash: echo "Stage 1, Job 1"
  - job: Job S1.J2
    steps:
    - bash: echo "Stage 1, Job 2"

- stage: Stage_2
  jobs:
  - job: Job S2.J1
    steps:
    - bash: echo "Stage 2, Job 1"
  - job: Job S1.J2
    steps:
    - bash: echo "Stage 2, Job 2"