parameters:
  - name: stages
    type: stageList
    default:
      - stage: Dynamic_Stage_1
        displayName: Dynamic Stage 1
        jobs:
        - job: Job_S1_J1
          displayName: Dynamic Stage 1 Job 1
          steps:
          - script: |
              echo "Stage 1, Job 1, Step 1"

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - multi-stage-looping-pipelines.yml

stages:

  # Run the pre-defined stages
  - stage: Dummy_Stage
    displayName: Dummy Stage
    jobs:
    - job: Dummy_Job
      displayName: Dummy Stage Dummy Job
      steps:
      - script: |
          echo "This is the dummy stage!"

  # Loop through any stages that were passed in
  - ${{ each stage in parameters.stages }}:
    - ${{ stage }}
