parameters:
  - name: 'stages'
    type: object
    default:
      - stage: Stage_1
        displayName: Stage 1
        jobs:
        - job: Job_S1_J1
          displayName: Stage 1 Job 1
          steps:
          - script: |
              echo "Stage 1, Job 1, Step 1"

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - multi-stage-looping-pipelines.yml

stages:
  - stage: Dummy_Stage
    displayName: Dummy Stage
    jobs:
    - job: Dummy_Job
      displayName: Dummy Stage Dummy Job
      steps:
      - script: |
          echo "This is the dummy stage!"

- ${{each stage in parameters.stages}}:
  - stage: ${{ stage.stage }} 
    displayName: ${{ stage.displayName}} 
    dependsOn: ${{ stage.dependsOn}} 
      