parameters:
- name: azureServiceConnection
  displayName: Azure Service Connection
  type: string
  values:
  - DummyConnection
  - My Azure Connection
  - Some Random Value

stages:
  - stage: Stage_1
    displayName: Stage 1

    jobs:

      - job: Job_S1_J1
        displayName: Stage 1 Job 1
        steps:
          - script: |
              echo "Outer Value: $(MyConnection)"
            displayName: Outer Echo

          - template: templates/create-resource-group.yml
            # parameters:
            #   azureServiceConnection: ${{ parameters.azureServiceConnection }}

          - task: AzureCLI@2
            displayName: Outer Template Step
            inputs:
              azureSubscription: ${{ parameters.azureServiceConnection }}
              addSpnToEnvironment: true
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                echo Here we go: ${{ parameters.azureServiceConnection }}