variables:
- name: blah
  value: "My Azure Connection"

stages:
  - stage: Stage_1
    displayName: Stage 1

    jobs:

      - job: Job_S1_J1
        displayName: Stage 1 Job 1
        steps:
          - script: |
              echo "Outer Value: $(service_connection_name)"
            displayName: Outer Echo

          - template: templates/create-resource-group.yml
            parameters:
              azureServiceConnection: $(service_connection_name)