variables:
- name: MyConnection
  value: "DummyConnection"

stages:
  - stage: Stage_1
    displayName: Stage 1

    jobs:

      - job: Job_S1_J1
        displayName: Stage 1 Job 1
        steps:
          - script: |
              echo "Outer Value: $(MyConnection)"
            displayName: Outer Echo

          - template: templates/create-resource-group.yml
            parameters:
              azureServiceConnection: $(MyConnection)

          - task: AzureCLI@2
            displayName: Outer Template Step
            inputs:
              # azureSubscription: $(MyConnection)
              azureSubscription: $(ServiceConnection)
              addSpnToEnvironment: true
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                echo Here we go: $(MyConnection)